version: '3.7'
services:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  mailhog2:
    image: mailhog/mailhog:latest
    ports:
      - "1026:1025"
      - "8026:8025"