version: '3.7'
services:
  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - "1025:1025"
      - "8025:1080"

  mailcatcher2:
    image: schickling/mailcatcher:latest
    ports:
      - "1026:1025"
      - "8026:1080"