version: "3.7"
services:
  gibbon-mail:
    image: stephaneklein/gibbon-mail:latest
    ports:
     - 5000:5000
    volumes:
     - ../mail-templates/:/templates/
    environment:
      SMTP_URL: smtp://user:password@mailcatcher:1025/?pool=true

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - "1025:1025"
      - "8025:1080"